oab_cookie_compliance.cookie_compliance:
  type: config_object
  label: 'Cookie compliance ddd'
  mapping:
    cookie_text:
      type: text
      label: 'Block text'
    cookie_link_text:
      type: label
      label: 'Link text'
    cookie_url:
      type: label
      label: 'Link URL'
