###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    memcached:
      image: memcached:alpine
      container_name: $CONTAINER_MEMCACHED
      networks:
        - memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: $CONTAINER_MAILHOG
      ports:
        - "${MAILHOG_PORT:-8025}:8025"
      networks:
        - mailhog

    mysql:
      image: mysql:8
      container_name: $CONTAINER_MYSQL
      volumes:
        - ${DB_DUMPS_DIR:-./data/db_dumps}:/tmp/db_dumps
        - ${MYSQL_DIR:-/var/lib/mysql}:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PWD
        MYSQL_DATABASE: $MARIADB_DB
        MYSQL_USER: $MARIADB_USER
        MYSQL_PASSWORD: $MARIADB_PWD
      ports:
        - "${MARIADB_EXTERNAL_PORT:-3306}:${MARIADB_PORT:-3306}"
      networks:
        - database

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql
      container_name: $CONTAINER_PHPMYADMIN
      ports :
        - "${PHPMYADMIN_PORT:-8080}:80"
      environment:
        PMA_HOST: "$CONTAINER_MYSQL"
      networks:
        - database

    nginx:
      build:
        context: config/docker/local/nginx
      container_name: $CONTAINER_NGINX
      working_dir: /application
      environment:
        CONTAINER_PHP_FPM: $CONTAINER_PHP_FPM
      depends_on:
        - php-fpm
      volumes:
        - .:/application
      ports:
        - "${APP_PORT:-8000}:80"
      networks:
        - proxy

    php-fpm:
      build:
        context: config/docker/local/php-fpm
        args:
          UID: $UID
          GID: $GID
      container_name: $CONTAINER_PHP_FPM
      working_dir: /application
      depends_on:
        - mysql
      volumes:
        - .:/application
        - ./config/docker/local/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        - ./config/docker/local/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        - ${DRUPAL_SITES_FILES_DIR:-./sites/default/files}:/application/sites/default/files
      networks:
        - proxy
        - database
        - mailhog
        - memcached

    testsamlidp_idp:
      image: kristophjunge/test-saml-idp
      container_name: $CONTAINER_SAMLTEST
      environment:
        SIMPLESAMLPHP_SP_ENTITY_ID: saml-poc
        SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: ${SAML_ASSERTION_CONSUMER_SERVICE:-http://localhost:8000}/en/saml/consume
      volumes:
        - ./config/docker/local/saml/users.php:/var/www/simplesamlphp/config/authsources.php
      ports:
        - "8081:8080"
        - "8443:8443"

networks:
    proxy:
    database:
    mailhog:
    memcached:
