idp:
  sso_qualif: sso_qualif
logout: false
logged_in_redirect: ''
update_email: false
update_language: false
no_account_authenticated_user_role: false
no_account_authenticated_user_account: null
force_authentication: true
force_saml_only: false
account_request_request_account: false
