status: true
dependencies:
  config:
    - system.menu.footer-br
  module:
    - language
    - system
  theme:
    - theme_boosted
id: footerbr
theme: theme_boosted
region: footer
weight: 0
provider: null
plugin: 'system_menu_block:footer-br'
settings:
  id: 'system_menu_block:footer-br'
  label: 'Footer BR'
  provider: system
  label_display: '0'
  level: 1
  depth: 0
visibility:
  language:
    id: language
    langcodes:
      pt-br: pt-br
    negate: false
    context_mapping:
      language: '@language.current_language_context:language_interface'
