tac_lite_categories:
  hub: hub
tac_lite_schemes: '2'
menu_rebuild_needed: true
_core:
  default_config_hash: O3rsbjEveBvnof1Hdq3ih8UBqlRN2betEk9OZhaiTPM
tac_lite_config_scheme_1:
  name: view
  perms:
    grant_view: grant_view
  unpublished: 0
  term_visibility: 1
  tac_lite_create: 0
tac_lite_grants_scheme_1:
  webform_manager:
    hub: {  }
  anonymous:
    hub:
      900: '900'
  webform_business_owner:
    hub: {  }
  authenticated:
    hub:
      900: '900'
  webform_admin:
    hub: {  }
  administrator:
    hub: {  }
  webform_spoc_securite:
    hub: {  }
  chief_editor:
    hub: {  }
  digital_admin:
    hub: {  }
  contributor:
    hub: {  }
  fh_backbones:
    hub: {  }
  dvi:
    hub: {  }
  chief_editor_hub:
    hub: {  }
  webform_business_analyst:
    hub: {  }
tac_lite_config_scheme_2:
  name: 'update and delete'
  perms:
    grant_update: grant_update
    grant_delete: grant_delete
  unpublished: 0
  term_visibility: 1
  tac_lite_create: 1
tac_lite_grants_scheme_2:
  anonymous:
    hub: {  }
  authenticated:
    hub: {  }
  administrator:
    hub: {  }
  chief_editor:
    hub: {  }
  digital_admin:
    hub: {  }
  webform_manager:
    hub: {  }
  contributor:
    hub: {  }
  fh_backbones:
    hub: {  }
  dvi:
    hub: {  }
  chief_editor_hub:
    hub: {  }
