features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: themes/theme_boosted/orange-business-services.png
favicon:
  use_default: 0
  path: themes/theme_boosted/favicon.ico
  mimetype: image/vnd.microsoft.icon
