oab_subhomes.subhomes:
  type: config_object
  label: 'Subhomes'
  mapping:
    press_term_tid:
      type: label
      label: 'Press term id'
    partner_term_tid:
      type: label
      label: 'Partner term id'
    customer_term_tid:
      type: label
      label: 'Customer term id'
    library_term_tid:
      type: label
      label: 'Library term id'
    blog_term_tid:
      type: label
      label: 'Blog term id'
    magazine_term_tid:
      type: label
      label: 'Magazine term id'
    product_term_tid:
      type: label
      label: 'Product term id'
    product_dvi_term_tid:
      type: label
      label: 'Product DVI term id'
    analysts_term_tid:
      type: label
      label: 'Analysts term id'
    press_meta:
      type: label
      label: 'Press meta title'
    partner_meta:
      type: label
      label: 'Partner meta title'
    customer_meta:
      type: label
      label: 'Customer meta title'
    library_meta:
      type: label
      label: 'Library meta title'
    blog_meta:
      type: label
      label: 'Blog meta title'
    magazine_meta:
      type: label
      label: 'Magazine meta title'
    product_meta:
      type: label
      label: 'Product meta title'
    analysts_meta:
      type: label
      label: 'Analysts meta title'
    distributor_term_tid:
      type: label
      label: 'Distributor term id'

oab_backoffice.pardot:
  type: config_object
  label: 'Pardot'
  mapping:
    pardot:
      label: 'Pardot'
      type: mapping
      mapping:
        iframe_url:
          type: label
          label: 'Iframe url'
    marketo:
      label: 'Marketo'
      type: mapping
      mapping:
        general:
          label: 'General'
          type: mapping
          mapping:
            mkto_domain:
              type: label
              label: 'Domain'
            mkto_munchkin_id:
              type: label
              label: 'Munchkin Id'
            mkto_version:
              type: label
              label: 'version'
            mkto_sous_domaine:
              type: label
              label: 'Sous domaine'
            mkto_univers_affichage:
              type: label
              label: 'Univers affichage'
        document:
          label: 'Document'
          type: mapping
          mapping:
            mkto_form_name:
              type: label
              label: 'Form name'
            mkto_form_id:
              type: label
              label: 'Form Id'
            mkto_custom_follow_up_url:
              type: label
              label: 'Custom follow up url'
            mkto_form_follow_up_message:
              type: text_format
              label: 'Form follow up message'


action.configuration.oab_backoffice_node_workbench_publish:
  type: action_configuration_default
  label: 'Node workbench publish'

action.configuration.oab_backoffice_node_workbench_unpublish:
  type: action_configuration_default
  label: 'Node workbench unpublish'

oab_backoffice.ece:
  type: config_object
  label: 'ECE'
  mapping:
    title:
      type: label
      label: 'Title'
    intro:
      type: label
      label: 'Intro'
    connect_txt:
      type: label
      label: 'Texte se connecter'
    connect_link:
      type: label
      label: 'Lien se connecter'
    discover_txt:
      type: label
      label: 'Texte découvrir'
    discover_link:
      type: label
      label: 'Lien découvrir'
    create_txt:
      type: label
      label: 'Texte créer compte'
    create_link:
      type: label
      label: 'Lien créer compte'
